### ISSUE TITLE
Official Docker image not working anymore

### ISSUE THREAD

**Issue by ad-si** [gibiansky/IHaskell#1208]
I followed the documentation on how to use the Docker image but I'm getting the error:

```txt
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
ihaskell: Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/base-4.13.0.0/Prelude.hi
    mismatched interface file versions (wanted "8065", got "8084")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/directory-1.3.6.0/System/Directory.hi
    mismatched interface file versions (wanted "8065", got "8084")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/unix-2.7.2.2/System/Posix/IO.hi
    mismatched interface file versions (wanted "8065", got "8084")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/base-4.13.0.0/System/IO.hi
    mismatched interface file versions (wanted "8065", got "8084")
Bad interface file: /home/jovyan/.stack/programs/x86_64-linux/ghc-8.8.4/lib/ghc-8.8.4/template-haskell-2.15.0.0/Language/Haskell/TH.hi
    mismatched interface file versions (wanted "8065", got "8084")
```

Also, before that error it is downloading ghc-8.8.4 when I use lts-16.23 in my `stack.yaml`, but it shouldn't download anything since lts-16.23 is already the same version as the one used for the Docker image.

**Comment by vaibhavsagar** [comment]
Hmm, can you post the command you ran? I just tried 

```
docker run --rm -p 8888:8888 gibiansky/ihaskell
```

and it seemed to work okay for me. It certainly shouldn't be downloading GHC 8.8.4. What IHaskell does is that it runs `stack env` to get the environment variables it needs, so something weird is probably happening there.

**Comment by vaibhavsagar** [comment]
Are you possibly using an older Docker image than the current one? I think that might explain the problems you are experiencing.

**Comment by ad-si** [comment]
> Are you possibly using an older Docker image than the current one? I think that might explain the problems you are experiencing.

Yeah, that's right 😅. Another reason why the docker container should be versioned: It's not immediately obvious which version you're running otherwise.

However, I still can't get it to run. No matter what my `stack.yaml` file looks like I get an `Could not find module ‘Graphics.Rendering.Chart.Easy’` error.

This seems to be the closets to correct so far:

```sh
docker run \
    --rm \
    --publish 8888:8888 \
    --volume "$PWD":/home/jovyan/work \
    gibiansky/ihaskell
```

```yaml
resolver: lts-16.23
packages:
    - .
    - ../ihaskell/ipython-kernel
    - ../ihaskell/ghc-parser
    - ../ihaskell/ihaskell-display/ihaskell-aeson
    - ../ihaskell/ihaskell-display/ihaskell-blaze
    - ../ihaskell/ihaskell-display/ihaskell-charts
    - ../ihaskell/ihaskell-display/ihaskell-diagrams
    - ../ihaskell/ihaskell-display/ihaskell-gnuplot
    - ../ihaskell/ihaskell-display/ihaskell-hatex
    - ../ihaskell/ihaskell-display/ihaskell-juicypixels
    - ../ihaskell/ihaskell-display/ihaskell-magic
    - ../ihaskell/ihaskell-display/ihaskell-plot
    - ../ihaskell/ihaskell-display/ihaskell-widgets
```
