### ISSUE TITLE
Support installing IHaskell kernel into a virtualenv

### ISSUE THREAD

**Issue by samdoshi** [gibiansky/IHaskell#566]
Jupyter has the option to install a kernel into a prefix directory instead of the user directory:

```jupyter kernelspec install -h```
```
...
--user
    Install to the per-user kernel registry
--replace
    Replace any existing kernel spec with this name.
--prefix=<Unicode> (InstallKernelSpec.prefix)
    Default: ''
    Specify a prefix to install to, e.g. an env. The kernelspec will be
    installed in PREFIX/share/jupyter/kernels/
...
```
The main use-case would be for installing a kernel inside a virtualenv as jupyter will add `{sys.prefix}/share/jupyter` to it's [data paths](http://jupyter.readthedocs.org/en/latest/system.html#data-files).

Would it be possible to update the `ihaskell install` command to accept a `--prefix` option to support this?

**Comment by gibiansky** [comment]
This would be useful. I will implement this (or accept a PR to do so).

**Comment by gibiansky** [comment]
I've implemented this on `master`. Would you mind trying it? It would be really great if you could also show me the commands you used; then I can put a "how to use jupyter in a virtualenv with ihaskell" in the  README.

**Comment by samdoshi** [comment]
It appears you can't use `--user` and `--prefix` at the same time

```sh
stack exec ihaskell -- install --prefix=env`
```
```
...
Exception: error running: /Users/sam/Scratch/ihaskell-in-a-virtualenv/env/bin/ipython kernelspec install --user /var/folders/g2/f3hmstnx0_df9nvmd5mz4phc0000gn/T/tmpThreadId416807282475249/haskell --replace --prefix env
exit status: 1
stderr: Can't specify both user and prefix. Please choose one or the other.
```

For you reference:
```sh
stack new ihaskell-in-a-virtualenv simple
cd ihaskell-in-a-virtualenv
```
You'll need to update the `stack.yaml` file:
```sh
cat stack.yaml
```
```yaml
flags: {}
packages:
    - '.'
    - location:
        git: git@github.com:gibiansky/IHaskell.git
        commit: fe89d49748ad10be7f668add04fd03771f619473
        valid-wanted: false
extra-deps:
    - ipython-kernel-0.7.0.0
resolver: lts-3.2
```
```sh
stack build
virtualenv env
source env/bin/activate
pip install jupyter==1.0.0
stack exec ihaskell -- install --prefix=env
jupyter --paths
jupyter notebook
```

Once you've got it working (I'd help but I've only been learning haskell for a few months now), I'd be more than happy to write something up a bit more proper to include in the readme.
