### ISSUE TITLE
Cannot install ihaskell-display widgets with stack

### ISSUE THREAD

**Issue by vaibhavsagar** [gibiansky/IHaskell#715]
I've built the `ihaskell-display/*` modules and installed `ihaskell` with `stack`, but I can't use any widget functionality and my attempts to import `IHaskell.Display.Widgets` are unsuccessful (Failed to load interface for ‘IHaskell.Display.Widgets’). Is there something simple I'm missing?

**Comment by schernichkin** [comment]
Thank you for closing my issue, now I'm going to close yours)

I did closer examination of how Stack works and why we have such behavior (it was an scenario in my issue which can be stably reproduced on current repo). 

**tl;dr;** To fix your must place stack.yaml to the folder with notebooks (or any parent folder). Stack.yaml should be like this:
```yaml
flags:
  ihaskell:
    binpkgdb: false
packages:
- location:
    git: https://github.com/gibiansky/IHaskell.git
    commit: f39b812fdcc5566210f9960f8218c5fc7fd40a77
  subdirs:
  - .
  - ./ipython-kernel
  - ./ghc-parser
  - ./ihaskell-display/ihaskell-aeson
  - ./ihaskell-display/ihaskell-blaze
  - ./ihaskell-display/ihaskell-charts
  - ./ihaskell-display/ihaskell-diagrams
  - ./ihaskell-display/ihaskell-gnuplot
  - ./ihaskell-display/ihaskell-hatex
  - ./ihaskell-display/ihaskell-juicypixels
  - ./ihaskell-display/ihaskell-magic
  - ./ihaskell-display/ihaskell-plot
  - ./ihaskell-display/ihaskell-static-canvas
  - ./ihaskell-display/ihaskell-widgets
extra-deps: []
resolver: lts-9.0
```

Or just run from the IHaskell directory. In this case everything under ihaskell-display/* will not work, because each directory contains it's own stack.yaml created under assumption that all other libraries are already installed, which is not true. Everything under other directories will work.

Let's turn to details. Stack maintains it environment by taking packages of specific GHC version (defined by resolver), then installed packages related to specific version of Stackage database, then custom packages, defined in stack.yaml and installed to project-local database (under .stack-work folder). Three statements can help clue the things together:
- Stack will not install to local Stackage cache anything what not belonging to the Stackage build plan. It's possible to have less installed packages than in Stackage database, but not more, neither different versions. When your build your project Stackage packages get installed to the local Stackage cache (if they are not already there) and become available to GHC. If you have not build your project yet they probably not yet there. 
- All additional libraries, specified in stack.yaml installed to project-local cache. They will work as they were a part of Stackage build plan, but only for the current project, completely isolated from any other projects.
- Stack looking for stack.yaml from the current to the parent folder, once it find it, it will use it. If it will not find it, it will use global-project configuration. Hence stack.yaml in child folder will completely override any parent folder's settings.
- (one more) `stack install` command may be misleading. Unlike cabal-install Stack do not have user package database (with the exception of global-project which is not very useful though). Thus `stack build` will perform an actual installation and it will only affect Stackage cache (and will only install what belongs to it) and project-local database. And `stack install` will just copy binaries.

Now back to IHaskell. To make IHaskell works all your need is working Haskell environment, IHaskell binary and Jupyter of course. So, if your just issue `stack install` your probably will not notice any problem. But display modules get loaded  dynamically using current environment. So, lets check environments:

`stack exec -- ghc-pkg list` under IHaskell folder (after building the project):
```
/home/username/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d
    Cabal-1.24.2.0
    array-0.5.1.1
    base-4.9.1.0
    binary-0.8.3.0
... more lines ...
/home/username/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/pkgdb
    Boolean-0.2.4
    Chart-1.8.2
    Chart-cairo-1.8.2
    HTTP-4000.3.7
... more lines ...
/home/username/Projects/IHaskell/.stack-work/install/x86_64-linux//8.0.2/pkgdb
    ghc-parser-0.1.8.0
    ihaskell-0.8.4.0
    ihaskell-aeson-0.3.0.0
    ihaskell-blaze-0.3.0.0
... more lines ...
```
As you can see, we have three section here: ghc-8.0.2 packages, Stackage database packages and IHaskell local packages. All IHaskell modules installed to project local database, IHaskell packages not included to lts-9.0, so issuing same command from different folder will return same first two sections, but without IHaskell packages:
```
/home/username/.stack/programs/x86_64-linux/ghc-8.0.2/lib/ghc-8.0.2/package.conf.d
    Cabal-1.24.2.0
    array-0.5.1.1
    base-4.9.1.0
    binary-0.8.3.0
... more lines ...
/home/username/.stack/snapshots/x86_64-linux/lts-9.0/8.0.2/pkgdb
    Boolean-0.2.4
    Chart-1.8.2
    Chart-cairo-1.8.2
    HTTP-4000.3.7
... more lines ...
/home/username/.stack/global-project/.stack-work/install/x86_64-linux/lts-9.0/8.0.2/pkgdb
    (no packages)
```
Running `stack exec -- ghc-pkg list` under ihaskell-widgets will yield similar results
```
  ...........
/home/username/Projects/IHaskell/ihaskell-display/ihaskell-widgets/.stack-work/install/x86_64-linux/lts-9.0/8.0.2/pkgdb
    (no packages)
```
This is because ihaskell-widgets has it's own stack.yaml, which does not include ihaskell modules and they also not in lts-9.0. So, if your enter Examples folder of ihaskell-widgets and try to run notebook, IHaskell will create kernel instance with Stack. Stack will search stack.yaml (or, possibly, just working directory, I'm not sure in exact behavior) an will find one of ihaskell-widgets. Which does not contain any IHaskell packages. Thus, attempt to import any IHaskell module will fail.
